# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Thu Jan 24 15:03:09 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1006, 606)
        self.centralwidget = QtGui.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.date_from_label = QtGui.QCheckBox(self.centralwidget)
        self.date_from_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.date_from_label.setObjectName("date_from_label")
        self.horizontalLayout.addWidget(self.date_from_label)
        self.date_from = QtGui.QDateEdit(self.centralwidget)
        self.date_from.setCalendarPopup(True)
        self.date_from.setObjectName("date_from")
        self.horizontalLayout.addWidget(self.date_from)
        self.date_to_label = QtGui.QCheckBox(self.centralwidget)
        self.date_to_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.date_to_label.setObjectName("date_to_label")
        self.horizontalLayout.addWidget(self.date_to_label)
        self.date_to = QtGui.QDateEdit(self.centralwidget)
        self.date_to.setCalendarPopup(True)
        self.date_to.setObjectName("date_to")
        self.horizontalLayout.addWidget(self.date_to)
        self.start = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMaximumSize(QtCore.QSize(50, 16777215))
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.stop = QtGui.QPushButton(self.centralwidget)
        self.stop.setMaximumSize(QtCore.QSize(50, 16777215))
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.post = QtGui.QPushButton(self.centralwidget)
        self.post.setMaximumSize(QtCore.QSize(50, 16777215))
        self.post.setObjectName("post")
        self.horizontalLayout.addWidget(self.post)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(512, 192))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.projects = QtGui.QTreeWidget(self.splitter)
        self.projects.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projects.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.projects.setProperty("showDropIndicator", False)
        self.projects.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.projects.setObjectName("projects")
        self.timers = QtGui.QTableView(self.splitter)
        self.timers.setProperty("showDropIndicator", False)
        self.timers.setSortingEnabled(True)
        self.timers.setCornerButtonEnabled(False)
        self.timers.setObjectName("timers")
        self.timers.horizontalHeader().setStretchLastSection(True)
        self.timers.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.splitter)
        mainwindow.setCentralWidget(self.centralwidget)
        self.actionStart = QtGui.QAction(mainwindow)
        self.actionStart.setObjectName("actionStart")
        self.actionPause = QtGui.QAction(mainwindow)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtGui.QAction(mainwindow)
        self.actionStop.setObjectName("actionStop")

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        mainwindow.setWindowTitle(QtGui.QApplication.translate("mainwindow", "qTimer v0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.date_from_label.setText(QtGui.QApplication.translate("mainwindow", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.date_to_label.setText(QtGui.QApplication.translate("mainwindow", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("mainwindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("mainwindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.post.setText(QtGui.QApplication.translate("mainwindow", "Post", None, QtGui.QApplication.UnicodeUTF8))
        self.projects.headerItem().setText(0, QtGui.QApplication.translate("mainwindow", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setText(QtGui.QApplication.translate("mainwindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setToolTip(QtGui.QApplication.translate("mainwindow", "Create a new timer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setShortcut(QtGui.QApplication.translate("mainwindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("mainwindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setToolTip(QtGui.QApplication.translate("mainwindow", "Pause a running timer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("mainwindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setToolTip(QtGui.QApplication.translate("mainwindow", "Stop a running timer (so it cannot be resumed later)", None, QtGui.QApplication.UnicodeUTF8))

