"""Initial Schema

Revision ID: 17c846bc28
Revises: None
Create Date: 2013-01-06 23:21:28.145354

"""

# revision identifiers, used by Alembic.
revision = '17c846bc28'
down_revision = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql.expression import func



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('synced_date', sa.DateTime(), server_default=func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('synced_date', sa.DateTime(), server_default=func.now(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('posted', sa.Boolean(), nullable=False),
    sa.Column('billable_status', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('timer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timer_id'], ['timers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('timers')
    op.drop_table('tickets')
    op.drop_table('projects')
    ### end Alembic commands ###
